export const moviesDatabase = [
  {
    id: 1,
    title: 'Interstellar',
    description:
      'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    movie_year: 2014,
    director: 'Christopher Nolan',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine', 'Casey Affleck', 'Mackenzie Foy', 'John Lithgow', 'Ellen Burstyn', 'Matt Damon'],
    rotten_tomatoes_score: '73%',
    age_rating: 'PG-13',
    movie_duration: 169,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    price: '120.00',
  },
  {
    id: 2,
    title: 'The Shawshank Redemption',
    description:
      'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    movie_year: 1994,
    director: 'Frank Darabont',
    actors: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler', 'Clancy Brown', 'Gil Bellows', 'Mark Rolston'],
    rotten_tomatoes_score: '89%',
    age_rating: 'R',
    movie_duration: 142,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    price: '110.00',
  },
  {
    id: 3,
    title: 'Inception',
    description:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    movie_year: 2010,
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page', 'Tom Hardy', 'Ken Watanabe', 'Dileep Rao', 'Cillian Murphy', 'Tom Berenger', 'Marion Cotillard'],
    rotten_tomatoes_score: '87%',
    age_rating: 'PG-13',
    movie_duration: 148,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    price: '115.00',
  },
  {
    id: 4,
    title: 'The Dark Knight',
    description:
      'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
    movie_year: 2008,
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Maggie Gyllenhaal', 'Gary Oldman', 'Morgan Freeman'],
    rotten_tomatoes_score: '94%',
    age_rating: 'PG-13',
    movie_duration: 152,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    price: '125.00',
  },
  {
    id: 5,
    title: 'Pulp Fiction',
    description:
      'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.',
    movie_year: 1994,
    director: 'Quentin Tarantino',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis', 'Ving Rhames', 'Harvey Keitel', 'Tim Roth', 'Amanda Plummer', 'Maria de Medeiros'],
    rotten_tomatoes_score: '92%',
    age_rating: 'R',
    movie_duration: 154,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    price: '105.00',
  },
  {
    id: 6,
    title: 'The Godfather',
    description:
      'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    movie_year: 1972,
    director: 'Francis Ford Coppola',
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Richard S. Castellano', 'Robert Duvall', 'Sterling Hayden', 'John Marley', 'Richard Conte', 'Diane Keaton'],
    rotten_tomatoes_score: '97%',
    age_rating: 'R',
    movie_duration: 175,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iVZ3JAcAjmguGPnRNfWFOtLHOuY.jpg',
    price: '130.00',
  },
  {
    id: 7,
    title: 'The Matrix',
    description:
      'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    movie_year: 1999,
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving', 'Joe Pantoliano', 'Marcus Chong', 'Julian Arahanga', 'Matt Doran', 'Gloria Foster'],
    rotten_tomatoes_score: '83%',
    age_rating: 'R',
    movie_duration: 136,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    price: '115.00',
  },
  {
    id: 8,
    title: 'Fight Club',
    description:
      'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.',
    movie_year: 1999,
    director: 'David Fincher',
    actors: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter', 'Meat Loaf', 'Jared Leto', 'Zach Grenier', 'Holt McCallany', 'Eion Bailey', 'Richmond Arquette'],
    rotten_tomatoes_score: '80%',
    age_rating: 'R',
    movie_duration: 139,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg',
    price: '120.00',
  },
  {
    id: 9,
    title: 'Forrest Gump',
    description:
      'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
    movie_year: 1994,
    director: 'Robert Zemeckis',
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Mykelti Williamson', 'Sally Field', 'Michael Conner Humphreys', 'Hanna Hall', 'Haley Joel Osment', 'Siobhan Fallon Hogan'],
    rotten_tomatoes_score: '76%',
    age_rating: 'PG-13',
    movie_duration: 142,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/h5J4W4veyxMXDMjeNxZI46TsHOb.jpg',
    price: '110.00',
  },
  {
    id: 10,
    title: 'Predator 2',
    description:
      'A police chief in the war-torn streets of Los Angeles discovers that an extraterrestrial creature is hunting down residents - and that he is the next target.',
    movie_year: 1990,
    director: 'Stephen Hopkins',
    actors: ['Danny Glover', 'Gary Busey', 'Kevin Peter Hall', 'Ruben Blades', 'Maria Conchita Alonso', 'Bill Paxton', 'Robert Davi', 'Adam Baldwin', 'Kent McCord'],
    rotten_tomatoes_score: '30%',
    age_rating: 'R',
    movie_duration: 108,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/83X4VwY9sdSJykskmsplIVG0a4h.jpg',
    price: '115.00',
  },
  {
    id: 11,
    title: 'Pirates of the Caribbean: Dead Man\'s Chest',
    description:
      'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davy Jones to avoid eternal damnation.',
    movie_year: 2006,
    director: 'Gore Verbinski',
    actors: ['Johnny Depp', 'Orlando Bloom', 'Keira Knightley', 'Stellan Skarsgård', 'Bill Nighy', 'Jack Davenport', 'Kevin McNally', 'Jonathan Pryce', 'Lee Arenberg'],
    rotten_tomatoes_score: '53%',
    age_rating: 'PG-13',
    movie_duration: 151,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uXEqmloGyP7UXAiphJUu2v2pcuE.jpg',
    price: '125.00',
  },
  {
    id: 12,
    title: 'Gladiator',
    description:
      'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    movie_year: 2000,
    director: 'Ridley Scott',
    actors: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed', 'Richard Harris', 'Derek Jacobi', 'Djimon Hounsou', 'David Schofield', 'John Shrapnel'],
    rotten_tomatoes_score: '80%',
    age_rating: 'R',
    movie_duration: 155,
    poster_url:
      'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    price: '120.00',
  },
  {
    id: 13,
    title: 'The Lion King',
    description: 'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: no worries for the rest of your days.',
    movie_year: 1994,
    director: 'Roger Allers, Rob Minkoff',
    actors: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones', 'Whoopi Goldberg', 'Rowan Atkinson', 'Moira Kelly', 'Nathan Lane', 'Ernie Sabella'],
    rotten_tomatoes_score: '92%',
    age_rating: 'G',
    movie_duration: 88,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
    price: '100.00',
  },
  {
    id: 14,
    title: 'Jurassic Park',
    description: 'During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.',
    movie_year: 1993,
    director: 'Steven Spielberg',
    actors: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum', 'Richard Attenborough', 'Bob Peck', 'Martin Ferrero', 'BD Wong', 'Joseph Mazzello', 'Ariana Richards', 'Samuel L. Jackson'],
    rotten_tomatoes_score: '92%',
    age_rating: 'PG-13',
    movie_duration: 127,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9i3plLl89DHMz7mahksDaAo7HIS.jpg',
    price: '105.00',
  },
  {
    id: 15,
    title: 'Titanic',
    description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    movie_year: 1997,
    director: 'James Cameron',
    actors: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Kathy Bates', 'Frances Fisher', 'Danny Nucci', 'Bill Paxton'],
    rotten_tomatoes_score: '88%',
    age_rating: 'PG-13',
    movie_duration: 194,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg',
    price: '120.00',
  },
  {
    id: 16,
    title: 'Avatar',
    description: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
    movie_year: 2009,
    director: 'James Cameron',
    actors: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang', 'Michelle Rodriguez'],
    rotten_tomatoes_score: '81%',
    age_rating: 'PG-13',
    movie_duration: 162,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg',
    price: '130.00',
  },
  {
    id: 17,
    title: 'The Avengers',
    description: 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
    movie_year: 2012,
    director: 'Joss Whedon',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Tom Hiddleston', 'Clark Gregg', 'Cobie Smulders', 'Stellan Skarsgård', 'Samuel L. Jackson'],
    rotten_tomatoes_score: '91%',
    age_rating: 'PG-13',
    movie_duration: 143,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    price: '150.00',
  },
  {
    id: 18,
    title: 'The Silence of the Lambs',
    description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    movie_year: 1991,
    director: 'Jonathan Demme',
    actors: ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney', 'Kasi Lemmons', 'Lawrence T. Wrentz', 'Scott Glenn', 'Anthony Heald', 'Frankie Faison'],
    rotten_tomatoes_score: '95%',
    age_rating: 'R',
    movie_duration: 118,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg',
    price: '125.00',
  },
  {
    id: 19,
    title: 'Schindler\'s List',
    description: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    movie_year: 1993,
    director: 'Steven Spielberg',
    actors: ['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes', 'Caroline Goodall', 'Jonathan Sagall', 'Embeth Davidtz'],
    rotten_tomatoes_score: '98%',
    age_rating: 'R',
    movie_duration: 195,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    price: '140.00',
  },
  {
    id: 20,
    title: 'The Departed',
    description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    movie_year: 2006,
    director: 'Martin Scorsese',
    actors: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson', 'Mark Wahlberg', 'Martin Sheen', 'Ray Winstone', 'Vera Farmiga', 'Anthony Anderson', 'Alec Baldwin'],
    rotten_tomatoes_score: '91%',
    age_rating: 'R',
    movie_duration: 151,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jyAgiqVSx5fl0NNj7WoGGKweXrL.jpg',
    price: '115.00',
  },
  {
    id: 21,
    title: 'Top Gun: Maverick',
    description: 'After more than thirty years of service as one of the Navy\'s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
    movie_year: 2022,
    director: 'Joseph Kosinski',
    actors: ['Tom Cruise', 'Val Kilmer', 'Miles Teller', 'Jennifer Connelly', 'Bashir Salahuddin', 'Jon Hamm', 'Charles Parnell', 'Monica Barbaro', 'Lewis Pullman'],
    rotten_tomatoes_score: '96%',
    age_rating: 'PG-13',
    movie_duration: 131,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    price: '160.00',
  },
  {
    id: 22,
    title: 'The Green Mile',
    description: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
    movie_year: 1999,
    director: 'Frank Darabont',
    actors: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse', 'Bonnie Hunt', 'James Cromwell', 'Michael Jeter', 'Graham Greene', 'Doug Hutchison', 'Sam Rockwell'],
    rotten_tomatoes_score: '79%',
    age_rating: 'R',
    movie_duration: 189,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
    price: '125.00',
  },
  {
    id: 23,
    title: 'Beverly Hills Cop: Axel F',
    description: 'Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.',
    movie_year: 2024,
    director: 'Mark Molloy',
    actors: ['Eddie Murphy', 'Joseph Gordon-Levitt', 'Taylour Paige', 'Judge Reinhold', 'John Ashton', 'Paul Reiser', 'Bronson Pinchot', 'Kevin Bacon', 'Luis Guzmán'],
    rotten_tomatoes_score: '65%',
    age_rating: 'R',
    movie_duration: 120,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zszRKfzjM5jltiq8rk6rasKVpUv.jpg',
    price: '150.00',
  },
  {
    id: 24,
    title: 'Star Wars: Episode IV - A New Hope',
    description: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire\'s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.',
    movie_year: 1977,
    director: 'George Lucas',
    actors: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 'Peter Cushing', 'Alec Guinness', 'Anthony Daniels', 'Kenny Baker', 'Peter Mayhew', 'David Prowse'],
    rotten_tomatoes_score: '93%',
    age_rating: 'PG',
    movie_duration: 121,
    poster_url: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
    price: '140.00',
  }
];
